import Head from "next/head";
import Image from "next/future/image";
import styles from "./login.module.css";
import logo from "../../public/logo/laurafinallogo.svg";
import { LoginForm } from "../../components/Login/LoginForm";

export default function LoginPage() {
  return (
    <div>
      <Head>
        <title>Laura Mac Method - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.loginFormContainer}>
        <div className={styles.loginProductContainer}></div>
        <div className={styles.formContainer}>
          <div className={styles.loginLogoContainer}>
            <Image
              className={styles.logo}
              src={logo}
              alt="logo"
              width={200}
              height="100%"
            />
          </div>
          <h1 className={styles.loginGreeting}>Welcome Back!</h1>
          <p className={styles.loginText}>
            “I can always see something of myself in <br></br> the characters I
            play.” - Mark Wahlberg
          </p>
          <LoginForm />
        </div>
      </div>
    </div>
  );
}
