import Head from "next/head";
import Image from "next/future/image";
import styles from "./register.module.css";
import logo from "../../public/logo/laurafinallogo.svg";
import { RegistrationForm } from "../../components/Register/RegistrationForm/RegistrationForm";
import Link from 'next/link';

export default function Register() {
  return (
    <div>
      <Head>
        <title>Laura Mac Method - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.registrationFormContainer}>
        <div className={styles.registrationProductContainer}></div>
        <div className={styles.formContainer}>
          <Link href="/">
            <div className={styles.registrationLogoContainer}>
              <Image
                className={styles.logo}
                src={logo}
                alt="logo"
                width={200}
                height="100%"
              />
            </div>
          </Link>
          <h1 className={styles.registrationGreeting}>
            Let&#39;s Get Started!
          </h1>
          <p className={styles.registrationText}>
            We just need some basic information to help <br></br> optimize your
            learning experience.
          </p>
          <RegistrationForm />
        </div>
      </div>
    </div>
  );
}
