import Head from 'next/head'
import Image from 'next/future/image'
import styles from '../styles/Home.module.css'
import {disney_logo, sony_logo, universal_logo, paramount_logo, lionsgate_logo} from '../public/partner_logos/partner_logos'
import Header from '../components/Navigation/Header'
import Laura_mac from '../public/home_pics/lm1.jpg'

export default function Home() {
  return (
    <div className={styles.container}>
      {/*****HEADER*****/}
      <Head>
        <title>Laura Mac Method - Acting School</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>

      </Header>
      {/*****HERO SECTION*****/}
      <section className={styles.heroSection}>
        <iframe className={styles.homeIframe} src={'https://player.vimeo.com/video/479896106?h=cde2d98eaa'}></iframe>
        <section className={styles.heroText}>
          <h1 className={styles.heroHeading}>We Build<br className={styles.break1}></br>Working Actors.<br className={styles.break2}></br></h1>
          <br></br>
          <p className={styles.heroParagraph}>We teach world-class acting to beginner,<br></br> intermediate, and advanced level actors across <br></br> the world both online and in-person.</p>
          <form className={styles.heroEmailForm}>
            <label for="email"></label>
            <input className={styles.emailInput} type="text" id="userEmail" name="email" placeholder="name@email.com"></input>
            <button className={styles.formButton1} display="block">Enroll in Classes FREE</button>
          </form>
        </section>
      </section>
      <section className={styles.partnerLogoContainer}>
        <p className={styles.partnerLogoText}>Our students have worked with the top 10+ major movie studios and counting</p>
        <div className={styles.partnerLogoImages}>
          <Image className={styles.disneyLogo} src={disney_logo} alt="disney logo"></Image>
          <Image className={styles.sonyLogo} src={sony_logo} alt="sony logo"></Image>
          <Image className={styles.universalLogo} src={universal_logo} alt="universal logo"></Image>
          <Image className={styles.paramountLogo} src={paramount_logo} alt="paramount logo"></Image>
          <Image className={styles.lionsgateLogo} src={lionsgate_logo} alt="lionsgate logo"></Image>
        </div>
      </section>
      <section className={styles.featuresContainer}>
        <Image className={styles.featurePic1} src={Laura_mac} alt="laura mac"></Image>
        <div className={styles.featureTextContainer}>
        <p className={styles.featureSubtitle1}>EXPLORE YOUR TALENTS</p>
        <p className={styles.featureTitle1}>Surpass audition expectations</p>
        <p className={styles.featureParagraph1}>Learn to control your nerves and perform to the best <br></br> of your ability at auditions.</p>
        </div>
      </section>
      {/*****FOOTER*****/}
      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
