import Head from 'next/head'
import Image from 'next/future/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import logo from '../public/logo/lauralogo1.svg'
import disney_logo from '../public/partner_logos/disney.png'
import sony_logo from '../public/partner_logos/sony.png'
import universal_logo from '../public/partner_logos/universal.png'
import paramount_logo from '../public/partner_logos/paramount.svg'
import lionsgate_logo from '../public/partner_logos/lionsgate.png'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className={styles.container}>
      {/*****HEADER*****/}
      <Head>
        <title>Laura Mac Method - Acting School</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        
      </Header>
      {/*****HERO SECTION*****/}
      <section className={styles.heroSection}>
        <iframe className={styles.homeIframe} src={'https://player.vimeo.com/video/479896106?h=cde2d98eaa'}></iframe>
        <section className={styles.heroText}>
          <h1 className={styles.heroHeading}>We Build<br className={styles.break1}></br>Working Actors.<br className={styles.break2}></br></h1>
          <br></br>
          <p className={styles.heroParagraph}>We teach world-class acting to beginner,<br></br> intermediate, and advanced level actors across <br></br> the world both online and in-person.</p>
          <form className={styles.heroEmailForm}>
            <label for="email"></label>
            <input className={styles.emailInput} type="text" id="userEmail" name="email" placeholder="name@email.com"></input>
            <button className={styles.formButton1} display="inline-block">Enroll in Classes FREE</button>
          </form>
        </section>
      </section>
      <section className={styles.partnerLogoContainer}>
        <Image className={styles.disneyLogo} src={disney_logo} alt="disney logo" layout="responsive"></Image>
        <Image className={styles.sonyLogo} src={sony_logo} alt="sony logo"></Image>
        <Image className={styles.universalLogo} src={universal_logo} alt="universal logo"></Image>
        <Image className={styles.paramountLogo} src={paramount_logo} alt="paramount logo"></Image>
        <Image className={styles.lionsgateLogo} src={lionsgate_logo} alt="lionsgate logo"></Image>
      </section>
      {/*****FOOTER*****/}
      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
