import Head from 'next/head'
import Header from '../../components/Dashboard/Navigation/Header/Header'
import styles from './dashboard.module.css'
import InfoNavBar from '../../components/Dashboard/InfoNav/InfoNav'
import Link from 'next/link'

export default function Dashboard() {
  return (
    <div className={styles.dashboardContainer}>
      {/*****HEADER*****/}
      <Head>
        <title>Laura Mac Method - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      {/*****SIDEBAR NAVIGATION*****/}
      <div className={styles.userDashboardContainer}>
        <div className={styles.infoSidebar}>
          <InfoNavBar></InfoNavBar>
        </div>
        <div className={styles.userDashboardNavBar}>
          <p className={styles.userGreeting}>Welcome back, Laura!</p>
          <p className={styles.lastLoggedIn}>Last Logged In: 1 day ago</p>
          <ul className={styles.dashboardNavItems}>
            <li className={styles.dashboardHomeButton}><Link href={'/'}><a className={styles.dashboardHomeText}>Home</a></Link></li>
            <li className={styles.dashboardClassesButton}><Link href={'/'}><a className={styles.dashboardHomeText}>Classes</a></Link></li>
            <li className={styles.dashboardCourseMaterialsButton}><Link href={'/'}><a className={styles.dashboardHomeText}>Course Materials</a></Link></li>
            <li className={styles.dashboardCommunityButton}><Link href={'/'}><a className={styles.dashboardHomeText}>Community</a></Link></li>
            <li className={styles.dashboardMessagesButton}><Link href={'/'}><a className={styles.dashboardHomeText}>Messages</a></Link></li>
          </ul>
        </div>
          <div className={styles.dashboardHeader}><h1>Home</h1></div>
          <div className={styles.dashboardMainContainer}>
            
              <div className={styles.courseProgressLessonContainer}>
                <h2 className={styles.courseProgressTitle}>Progress</h2>
              </div>

              <div className={styles.courseNotificationsContainer}>
                <h2 className={styles.courseNotificationsTitle}>Notifications</h2>
              </div>
    
              <div className={styles.courseNewsContainer}>
                <h2 className={styles.courseNewsTitle}>News & Updates</h2>
              </div>

          <div className={styles.newsAndAnnouncements}></div>
          <div className={styles.quizzesContainer}>
            <div className={styles.quizzesCompleted}></div>
            <div className={styles.avgQuizScore}></div>
          </div>
          <div className={styles.awardsAndRecognitionContainer}>
            <div className={styles.userBadges}></div>
            <div className={styles.userClassAttendance}></div>
          </div>
          <div className={styles.userProgressTree}></div>
          </div>
        </div>
    </div>
  )
}