import Head from 'next/head'
import Header from '../../components/Navigation/Header/Header'
import styles from './dashboard.module.css'
import InfoNavBar from '../../components/Dashboard/InfoNav/InfoNav'

export default function Dashboard() {
  return (
    <div className={styles.dashboardContainer}>
      {/*****HEADER*****/}
      <Head>
        <title>Laura Mac Method - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      {/*****SIDEBAR NAVIGATION*****/}
      <div className={styles.userDashboardContainer}>
        <div className={styles.infoSidebar}>
          <InfoNavBar></InfoNavBar>
        </div>
        <div className={styles.dashboardNavBar}>
          <p>Welcome back, Laura!</p>
          <p>Last Logged In: 1 day ago</p>
          <ul>
            <li>Home</li>
            <li>Classes</li>
            <li>Course Materials</li>
            <li>Messages</li>
          </ul>
        </div>
          <div className={styles.dashboardHeader}></div>
          <div className={styles.courseProgress}></div>
          <div className={styles.userNotifications}></div>
          <div className={styles.newsAndAnnouncements}></div>
          <div className={styles.quizzesContainer}>
            <div className={styles.quizzesCompleted}></div>
            <div className={styles.avgQuizScore}></div>
          </div>
          <div className={styles.awardsAndRecognitionContainer}>
            <div className={styles.userBadges}></div>
            <div className={styles.userClassAttendance}></div>
          </div>
          <div className={styles.userProgressTree}></div>
      </div>
    </div>
  )
}