import Head from 'next/head'
import Header from '../../components/Navigation/Header/Header'
import styles from '../../styles/Home.module.css'

export default function Dashboard() {
  return (
    <div className={styles.dashboardContainer}>
      {/*****HEADER*****/}
      <Head>
        <title>Laura Mac Method - Acting School</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      {/*****SIDEBAR NAVIGATION*****/}
    </div>
  )
}