import Image from "next/future/image";
import Head from "next/head";
import InfoNavBar from "../../../components/Dashboard/InfoNav/InfoNav";
import DashboardNavBar from "../../../components/Dashboard/MainNav/MainNav";
import DashboardTitle from "../../../components/Dashboard/DashboardTitle/DashboardTitle";
import Header from "../../../components/Navigation/Header/Header";
import styles from "./settings.module.css";
import Avatar from '../../../public/icons/dashboard_icons/avatar.png'

const links = [
  { label: "One on One Coaching", href: "" },
  { label: "About", href: "" },
  { label: "Blog", href: "" },
  { label: "Log out", href: "/api/logout" },
  { label: "Upgrade plan", href: "", useButtonStyle: true },
];

export default function Dashboard() {
  return (
    <div className={styles.dashboardContainer}>
      {/*****HEADER*****/}
      <Head>
        <title>Laura Mac Method - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        links={links}
        navContainer="navContainerDashboard"
        navUl="navUlDashboard"
        logoStyling="logo2Dashboard"
      />
      {/*****USER DASHBOARD SIDEBAR NAVIGATION*****/}
      <div className={styles.infoSidebar}>
        <InfoNavBar></InfoNavBar>
      </div>
      {/*****USER DASHBOARD MAIN NAVIGATION*****/}
      <DashboardNavBar></DashboardNavBar>
      {/*****USER DASHBOARD HEADER TITLE*****/}
      <DashboardTitle title={"Dashboard"} subTitle={"User Settings"}></DashboardTitle>
      {/*****USER DASHBOARD CARD CONTAINER*****/}
      <div className={styles.dashboardMainContainer}>
        {/*****USER ACCOUNT SETTINGS*****/}
        <div className={styles.accountSettingsContainer}>
          <h2 className={styles.accountSettingsTitle}>
            Profile Settings
          </h2>
          {/*****EDIT PROFILE PIC*****/}
          <div className={styles.editProfilePicContainer}>
            <Image src={Avatar} alt="avatar" width={48}></Image>
            <p className={styles.editProfilePicText}>Edit profile pic</p>
          </div>
          {/*****BASIC PROFILE INFO*****/}
          <div className={styles.profileInfoContainer}>
            <div className={styles.firstNameContainer}>
              <p className={styles.firstNameText}>First name:</p>
              <input className={styles.firstNameInput}></input>
            </div>
            <div className={styles.lastNameContainer}>
              <p className={styles.lastNameText}>Last name:</p>
              <input className={styles.lastNameInput}></input>
            </div>
            <div className={styles.emailAddressContainer}>
              <p className={styles.emailAddressText}>Email address:</p>
              <input className={styles.lastNameInput}></input>
            </div>
          <div className={styles.experienceSelectionContainer}>
            <p className={styles.experienceLevelText}>Experience Level</p>
            <select className={styles.experienceSelection}>
              <option>Beginner</option>
              <option>Intermediate</option>
              <option>Advanced</option>
            </select>
          </div>
        </div>
          <div className={styles.lineBreak}></div>
        {/*****SUBSCRIPTION & BILLING SETTINGS*****/}
        <div>
          <h2 className={styles.accountSettingsTitle}>
            Subscription & Billing Information
          </h2>
          <div className={styles.subscriptionPlanContainer}>
            <p className={styles.subscriptionPlanText}>Subscription plan: Academy (monthly)</p>
          </div>
          <div className={styles.cardInfoContainer}>
            <p className={styles.cardInformationText}>Card information:</p>
            <p className={styles.cardEditText}>Click here to edit card information</p>
          </div>
          <div className={styles.changePlanButton}>
            <p className={styles.editText}>Change Plan</p>
          </div>
          </div>
          <div className={styles.lineBreak}></div>
          <h2 className={styles.accountSettingsTitle}>
            Account Settings
          </h2>
          <div className={styles.passwordContainer}>
            <p className={styles.passwordText}>Password:</p>
            <p className={styles.editText}>Change Password</p>
          </div>
        </div>
      </div>
    </div>
  );
}
